services:

  traefik:
    image: traefik:v3.6
    container_name: extractext_traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
      - "--api.insecure=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - extractext_net

  mongo:
    image: mongo:7
    container_name: extractext_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - extractext_net

  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: extractext_app
    restart: unless-stopped
    environment:
      MONGODB_URL: mongodb://extractext_mongo:27017
      MONGODB_DB_NAME: extractext
      PDF_MAX_SIZE_MB: 10
    depends_on:
      - mongo
    networks:
      - extractext_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.extractext.rule=Host(`extractext.localhost`)"
      - "traefik.http.routers.extractext.entrypoints=web"
      - "traefik.http.services.extractext.loadbalancer.server.port=8000"

volumes:
  mongo_data:

networks:
  extractext_net:
    driver: bridge